blas:
  - openblas    # [not osx]
  - mkl         # [not osx]
  - accelerate  # [osx]
cxx_compiler:
  - clangxx     # [linux64 or osx]
cxx_compiler_version:
  - 19          # [linux64 or osx]
mkl:
  - '2025'
mkl_devel:
  - '2025'