{% set name = "pyinterp" %}
{% set version = "2024.11.0" %}
{% set sha256 = "65d6f8b380ebccc6387147297d87b7013c92c3961cdf2c3fcc5935b1e6bae6d0" %}
{% set build = 0 %}

{% if "osx" in target_platform %}
{% set blas = "" %}
{% endif %}
# recipe-lint fails if blas is undefined
{% set blas = blas or "openblas" %}
{% if blas == "openblas" %}
# prioritize openblas via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CNES/pangeo-{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  {% if blas == "openblas" or "osx" in target_platform %}
  {% set mkl_option = "no" %}
  {% else %}
  {% set mkl_option = "yes" %}
  {% endif %}
  number: {{ build }}
  {% if target_platform == "win-64" %}
  script: {{ PYTHON }} -m pip install . -vv -Cmkl={{ mkl_option }}" -Cgenerator="Visual Studio 17 2022"
  {% else %}
  script: {{ PYTHON }} -m pip install . -vv -Cmkl={{ mkl_option }}"
  {% endif %}
  skip: true  # [linux32 or win32 or py<310 or (arm64 and blas != "openblas")]

  {% if blas == "openblas" %}
  {% if win or linux %}
  {% set blas_prefix = "openblas_" %}
  {% else %}
  {% set blas_prefix = "" %}  # For osx, dot not use a prefix, because we use the system blas (accelerate)
  {% endif %}
  {% else %}
  {% set blas_prefix = "mkl_" %}
  {% endif %}
  string: {{ blas_prefix }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}

  ignore_run_exports:
    - mkl                                 # [blas == "mkl"]
    - openblas                            # [(blas == "openblas") and (win or linux)]

requirements:
  build:
    - python >=3.10                       # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - setuptools
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make                                # [linux]
  host:
    - dask
    - eigen
    - libboost-devel >=1.79.0
    - mkl-devel                           # [blas == "mkl"]
    - openblas                            # [(blas == "openblas") and (win or linux)]
    - numpy
    - pip
    - pytest
    - python
    - setuptools
    - xarray
  run:
    - dask *
    - mkl *                               # [blas == "mkl"]
    - openblas *                          # [(blas == "openblas") and (win or linux)]
    - python
    - xarray >=0.13

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs pyinterp

about:
  home: https://github.com/CNES/pangeo-pyinterp
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for optimized geo-referenced interpolation

  description: |
    Tools for interpolating geo-referenced data used in the field of
    geosciences. There are other libraries that cover this problem, but written
    entirely in Python, the performance of these projects was not quite
    sufficient for our needs. That is why this project was created.
  doc_url: https://pangeo-pyinterp.readthedocs.io/
  dev_url: https://github.com/CNES/pangeo-pyinterp

extra:
  recipe-maintainers:
    - fbriol
