{% set name = "pyinterp" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CNES/pangeo-{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: f7a6a612a264f98d6f1ba3ea9b305c98291ef08629304f73b2e202e133ff8da6

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [linux32 or win32 or py<36]

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux or osx]
    - vs2017_win-64          # [win]
    - cmake==3.16.3  # workarounds a bug in Windows with v3.16.4
  host:
    - eigen
    - gsl
    - boost-cpp
    - mkl
    - mkl-devel
    - numpy
    - pip
    - pytest
    - python
    - setuptools
    - xarray
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - libblas * *mkl  # [linux or osx]
    - mkl  # [win]
    - xarray

test:
  imports:
    - pyinterp.core

about:
  home: https://github.com/CNES/pangeo-pyinterp
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'Python library for optimized geo-referenced interpolation'

  description: |
    Tools for interpolating geo-referenced data used in the field of
    geosciences. There are other libraries that cover this problem, but written
    entirely in Python, the performance of these projects was not quite
    sufficient for our needs. That is why this project was created.
  doc_url: https://pangeo-pyinterp.readthedocs.io/
  dev_url: https://github.com/CNES/pangeo-pyinterp

extra:
  recipe-maintainers:
    - fbriol
