{% set name = "pyinterp" %}
{% set version = "0.3.2" %}
{% set build = 2 %}

# recipe-lint fails if blas is undefined
{% set blas = blas or 'openblas' %}
{% if blas == "openblas" %}
# prioritize openblas via build number
{% set build = build + 100 %}
{% endif %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CNES/pangeo-{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4a0a052c14b2eb5b92aa0fe74c7026951194d5daa649095ef5978b58c4bfe77

build:
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [linux32 or win32 or py<36]

  {% if blas != 'openblas' %}
  {% set blas_prefix = "openblas" %}
  {% else %}
  {% set blas_prefix = "mkl" %}
  {% endif %}
  string: "{{ blas_prefix }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}"

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux or osx]
    - vs2017_win-64          # [win]
    - cmake
  host:
    - eigen
    - gsl
    - boost-cpp
    - mkl  # [blas == 'mkl']
    - mkl-devel  # [blas == 'mkl']
    - openblas  # [blas == 'openblas']
    - numpy
    - pip
    - pytest
    - python
    - setuptools
    - xarray
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - libblas * *mkl  # [(linux or osx) and (blas == 'mkl')]
    - mkl  # [win and (blas == 'mkl')]
    - libblas * *openblas  # [blas == 'openblas']
    - xarray

test:
  imports:
    - pyinterp.core

about:
  home: https://github.com/CNES/pangeo-pyinterp
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for optimized geo-referenced interpolation

  description: |
    Tools for interpolating geo-referenced data used in the field of
    geosciences. There are other libraries that cover this problem, but written
    entirely in Python, the performance of these projects was not quite
    sufficient for our needs. That is why this project was created.
  doc_url: https://pangeo-pyinterp.readthedocs.io/
  dev_url: https://github.com/CNES/pangeo-pyinterp

extra:
  recipe-maintainers:
    - fbriol
