{% set name = "pyinterp" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CNES/pangeo-{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6645122a8fb2d6119e16a43a20c40b40a5b6781e0a4a33d185746e9d2535f64e

build:
  number: 0
  skip: true  # [linux32 or win32 or py<36]

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux or osx]
    - vs2017_win-64          # [win]
    - cmake
  host:
    - eigen
    - gsl
    - boost-cpp
    - numpy
    - python
    - setuptools
    - xarray
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - xarray

test:
  imports:
    - pyinterp.core

about:
  home: https://github.com/CNES/pangeo-pyinterp
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'Python library for optimized geo-referenced interpolation'

  description: |
    Tools for interpolating geo-referenced data used in the field of
    geosciences. There are other libraries that cover this problem, but written
    entirely in Python, the performance of these projects was not quite
    sufficient for our needs. That is why this project was created.
  doc_url: http://simplejson.readthedocs.io/
  doc_url: https://pangeo-pyinterp.readthedocs.io/
  dev_url: https://github.com/CNES/pangeo-pyinterp

extra:
  recipe-maintainers:
    - fbriol
