{% set name = "pyinterp" %}
{% set version = "2025.11.0" %}
{% set sha256 = "0c82a7ecc5759d0f3e60cc6aefddccab3e3399f8d9b047d07a1445e75deb4b91" %}
{% set build = 0 %}

# Set blas to "openblas" if not already set
{% set blas = blas or "openblas" %}
{% if blas == "openblas" %}
# Prioritize openblas via build number
{% set build = build + 100 %}
{% endif %}
# Set mkl_option to "yes" if blas is "mkl"
{% if blas != "mkl" %}
{% set mkl_option = "no" %}
{% else %}
{% set mkl_option = "yes" %}
{% endif %}
# Define the generator for the build
{% if target_platform == "win-64" %}
{% set generator = "-Cgenerator=\"Visual Studio 17 2022\"" %}
{% else %}
{% set generator = "" %}
{% endif %}
# Define the prefix for the package name
{% if blas == "openblas" or osx %}
{% if win or linux %}
{% set blas_prefix = "openblas_" %}
{% else %}
# For OSX, dot not use a prefix, because we use the system blas (accelerate)
{% set blas_prefix = "" %}
{% endif %}
{% else %}
{% set blas_prefix = "mkl_" %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://github.com/CNES/pangeo-{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  url: https://files.catbox.moe/at6nzr.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation -Cmkl={{ mkl_option }} {{ generator }}
  skip: true  # [linux32 or win32 or py<311 or (blas == "mkl" and (linux_aarch64 or linux_ppc64le))]
  string: {{ blas_prefix }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}

  ignore_run_exports:
    - xarray
    - numpy
    - libboost
    - python

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make                                # [linux or osx]
  host:
    - dask
    - eigen
    - libboost-devel >=1.79.0
    - mkl-devel                           # [blas == "mkl"]
    - openblas                            # [(blas == "openblas") and (win or linux)]
    - blas * accelerate                   # [osx]
    - numpy
    - pip
    - pytest
    - python
    - setuptools
    - xarray
  run:
    - dask *
    - mkl *                               # [blas == "mkl"]
    - openblas *                          # [(blas == "openblas") and (win or linux)]
    - blas * accelerate                   # [osx]
    - python
    - xarray >=0.13

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs pyinterp

about:
  home: https://github.com/CNES/pangeo-pyinterp
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python library for optimized geo-referenced interpolation

  description: |
    Tools for interpolating geo-referenced data used in the field of
    geosciences. There are other libraries that cover this problem, but written
    entirely in Python, the performance of these projects was not quite
    sufficient for our needs. That is why this project was created.
  doc_url: https://cnes.github.io/pangeo-pyinterp/
  dev_url: https://github.com/CNES/pangeo-pyinterp

extra:
  recipe-maintainers:
    - fbriol
