schema_version: 1

context:
  name: pyinterp
  version: 2025.11.0
  sha256: 1bc00696ffb82e06043d64b887179b86d4e9c7acf43ceb73a7243baabdd1892c

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/CNES/pangeo-${{ name }}/releases/download/${{ version }}/${{ name }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  skip:
    - (aarch64 or ppc64le) and blas == "mkl"
  number: 0
  string: ${{ blas }}${{ hash }}_${{ build_number }}
  variant:
    down_prioritize_variant: ${{ 1 if blas == "mkl" else 0 }}
  script: '${{ PYTHON }} -m pip install . -vv --no-build-isolation -Cmkl=${{ "yes" if blas == "mkl" else "no" }} ${{ "-Cgenerator=\"Visual Studio 17 2022\"" if win else "" }}'

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - setuptools
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - if: linux or osx
      then: make
  host:
    - dask
    - libboost-devel >=1.79.0
    - if: blas == "mkl"
      then: mkl-devel
    - if: (blas == "openblas") and (win or linux)
      then: openblas
    - if: osx
      then: blas * accelerate
    - numpy
    - pip
    - pytest
    - python
    - setuptools
    - xarray
  run:
    - dask *
    - if: blas == "mkl"
      then: mkl *
    - if: (blas == "openblas") and (win or linux)
      then: openblas *
    - if: osx
      then: blas * accelerate
    - python
    - xarray >=0.13
  ignore_run_exports:
    from_package:
      - xarray
      - numpy
      - libboost

tests:
  - requirements:
      run:
        - pytest
    script:
      # The --measure-coverage option limits the number of samples processed
      # during tests, reducing the time needed for coverage reports. This option
      # is enabled here to reduce CI execution time.
      - TEST_DIR=$(python -c "import pyinterp; from pathlib import Path; print(Path(pyinterp.__file__).parent / 'tests')")
      - pytest -q "$TEST_DIR" --measure-coverage

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python library for optimized geo-referenced interpolation
  description: |
    Tools for interpolating geo-referenced data used in the field of
    geosciences. There are other libraries that cover this problem, but written
    entirely in Python, the performance of these projects was not quite
    sufficient for our needs. That is why this project was created.
  homepage: https://github.com/CNES/pangeo-pyinterp
  repository: https://github.com/CNES/pangeo-pyinterp
  documentation: https://cnes.github.io/pangeo-pyinterp/

extra:
  recipe-maintainers:
    - fbriol
