schema_version: 1

context:
  name: pyinterp
  version: 2025.11.0
  sha256: 79a42e86b41607d6a11988264661c0997f615218bafdfd8836ec1fe3e071073e
  build: 0
  blas: openblas

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/CNES/pangeo-${{ name }}/releases/download/${{ version }}/${{ name }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: |-
    {% set build_num = build %}
    {% if blas == "openblas" %}
      {% set build_num = build_num + 100 %}
    {% endif %}
    {{ build_num }}
  string: |-
    {% set blas_prefix = "" %}
    {% if blas == "openblas" and (win or linux) %}
      {% set blas_prefix = "openblas_" %}
    {% elif blas == "mkl" %}
      {% set blas_prefix = "mkl_" %}
    {% endif %}
    {{ blas_prefix }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}
  skip: linux32 or win32 or python_impl == 'pypy' or python < '3.10' or (blas == "mkl" and (linux_aarch64 or linux_ppc64le))
  script: |-
    {% set mkl_option = "yes" if blas == "mkl" else "no" %}
    {% set generator = "-Cgenerator=\"Visual Studio 17 2022\"" if target_platform == "win-64" else "" %}
    {{ PYTHON }} -m pip install . -vv --no-build-isolation -Cmkl={{ mkl_option }} {{ generator }}
  ignore_run_exports:
    by_name:
      - xarray
      - numpy
      - libboost
      - python

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: setuptools
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - if: linux or osx
      then: make
  host:
    - dask
    - libboost-devel >=1.79.0
    - if: blas == "mkl"
      then: mkl-devel
    - if: (blas == "openblas") and (win or linux)
      then: openblas
    - if: osx
      then: blas * accelerate
    - numpy
    - pip
    - pytest
    - python
    - setuptools
    - xarray
  run:
    - dask *
    - if: blas == "mkl"
      then: mkl *
    - if: (blas == "openblas") and (win or linux)
      then: openblas *
    - if: osx
      then: blas * accelerate
    - python
    - xarray >=0.13

tests:
  - requirements:
      run:
        - pytest
    script:
      - pytest --pyargs pyinterp

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python library for optimized geo-referenced interpolation
  description: |
    Tools for interpolating geo-referenced data used in the field of
    geosciences. There are other libraries that cover this problem, but written
    entirely in Python, the performance of these projects was not quite
    sufficient for our needs. That is why this project was created.
  homepage: https://github.com/CNES/pangeo-pyinterp
  repository: https://github.com/CNES/pangeo-pyinterp
  documentation: https://cnes.github.io/pangeo-pyinterp/

extra:
  recipe-maintainers:
    - fbriol
